# Google Cloud Run configuration
# This gives us REAL infrastructure, not toy hosting

runtime: nodejs18

# PROPER resources - not Vercel's pathetic limits
instance_class: F4
automatic_scaling:
  min_instances: 1
  max_instances: 100
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65

# Environment variables
env_variables:
  NODE_ENV: "production"
  PORT: "8080"

# Handlers for Next.js
handlers:
  - url: /_next/static
    static_dir: .next/static
    secure: always
    
  - url: /.*
    script: auto
    secure: always

# VPC connector for Firebase (if using private IPs)
# vpc_access_connector:
#   name: projects/PROJECT_ID/locations/REGION/connectors/CONNECTOR_NAME