#!/bin/bash

echo "🚂 Deploying to Railway (Fuck Vercel!)"
echo "====================================="
echo ""
echo "Option 1: Railway (Easiest)"
echo "1. Install Railway CLI: brew install railwayapp/tap/railway"
echo "2. Run: railway login"
echo "3. Run: railway init"
echo "4. Run: railway up"
echo ""
echo "Option 2: Fly.io (More control)"
echo "1. Install Fly CLI: brew install flyctl"
echo "2. Run: flyctl auth login"
echo "3. Run: flyctl launch"
echo "4. Run: flyctl deploy"
echo ""
echo "Option 3: Google Cloud Run (Already have Firebase)"
echo "1. Install gcloud CLI: brew install google-cloud-sdk"
echo "2. Run: gcloud auth login"
echo "3. Run: gcloud run deploy leila-frontend --source . --region us-central1"
echo ""
echo "Option 4: Self-hosted VPS"
echo "1. Get a VPS (DigitalOcean, Linode, etc)"
echo "2. Run: docker build -t leila-app ."
echo "3. Run: docker run -p 80:3000 leila-app"
echo ""
echo "Which option do you want? Railway is literally 2 commands and done."