#!/bin/bash

echo "Setting up crm.heyleila.com with Firebase Hosting..."

# Add custom domain to Firebase hosting
echo "Adding custom domain to Firebase..."
firebase hosting:customdomain:create crm.heyleila.com --site leila-crm --project leila-platform

echo ""
echo "📋 MANUAL DNS CONFIGURATION REQUIRED:"
echo ""
echo "Please add the following DNS records in your GoDaddy DNS settings:"
echo ""
echo "1. Add CNAME record:"
echo "   Type: CNAME"
echo "   Name: crm"
echo "   Value: leila-crm.web.app"
echo "   TTL: 600 (10 minutes)"
echo ""
echo "2. Or add A records (if CNAME doesn't work):"
echo "   Type: A"
echo "   Name: crm"
echo "   Value: 199.36.158.100"
echo "   TTL: 600"
echo ""
echo "   Type: A"  
echo "   Name: crm"
echo "   Value: 199.37.158.100"
echo "   TTL: 600"
echo ""
echo "🔗 Access GoDaddy DNS settings at:"
echo "   https://dcc.godaddy.com/manage/heyleila.com/dns"
echo ""
echo "⏱️  DNS propagation may take up to 24 hours"
echo "🌐 Once configured, the CRM will be available at: https://crm.heyleila.com"
echo ""
echo "🔍 Check status with:"
echo "   firebase hosting:customdomain:list --project leila-platform"
echo ""
echo "📊 Current CRM URL (temporary): https://leila-crm.web.app"